### ISSUE TITLE
Bug in battery percentage.

### ISSUE THREAD

**Issue by Fenshu28** [ShimmerEngineering/ShimmerJavaExamples#9]
Hello, I am having a problem with the way it shows me the battery percentage, when I connect to the device it shows me the percentage correctly but when I start transmitting the percentage bar goes crazy :(, it alternates between several values.
 I don't know if I'm making a mistake when getting and updating the battery percentage.
 I am attaching evidence and I hope you can help me. Thank you very much in advance for your assistance.

- I have a thread that updates my Frame components.
![imagen](https://github.com/ShimmerEngineering/ShimmerJavaExamples/assets/107078871/a7facb78-c96e-47c5-8329-dbec17c15d0b)
![imagen](https://github.com/ShimmerEngineering/ShimmerJavaExamples/assets/107078871/e15ea3fc-50ee-470b-8655-244b580a52a8)

- I obtain the battery percentage like this, in these 2 ways.
![imagen](https://github.com/ShimmerEngineering/ShimmerJavaExamples/assets/107078871/a5c1df45-89b8-4f6f-8343-144e69eb7d4c)

- When the device is initialized it starts transmitting:
![imagen](https://github.com/ShimmerEngineering/ShimmerJavaExamples/assets/107078871/d690a97c-7cc0-4b5d-a222-2fc31be92b4f)

Video of how it behaves:
https://github.com/ShimmerEngineering/ShimmerJavaExamples/assets/107078871/98d2efe3-7d6c-4611-965a-f1c2a446bdad

**Comment by Fenshu28** [comment]
Hello, apologies, I would like to know if this bug has a solution or if I am doing things wrong, because I have looked everywhere for documentation and can't find anything.
Tanks <3

**Comment by JongChern** [comment]
apologies for the delay, can you show me how you are setting up the device (e.g. in terms of configuration what sensors you are enabling, sampling rate etc). Just so I understand you are commenting about the behavior of how the battery level is changing?

**Comment by JongChern** [comment]
Just to give a bit of an understanding, the battery voltage is read via ADC. The ADC is read every new sample, please see below for the relevant code
https://github.com/ShimmerEngineering/Shimmer-Java-Android-API/blob/master/ShimmerDriver/src/main/java/com/shimmerresearch/driver/ShimmerObject.java#L1143

As the Shimmer device goes through many operations, it is normal for the values to fluctuate, I would recommend averaging out the values to get a more consistent value. I hope that helps.
